CC = gcc
CFLAGS = -Wall -Werror

# TODO: add wireminnow-part8
all: discard-server discard-client

wireminnow-part8: wireminnow-part8.c
	# TODO: Add compilation command for wireminnow-part8
	# Hint: Use $(CC) with $(CFLAGS)

discard-server: discard-server.c
	$(CC) $(CFLAGS) -o discard-server discard-server.c

discard-client: discard-client.c
	$(CC) $(CFLAGS) -o discard-client discard-client.c

clean:
	# TODO: add wireminnow-part8
	rm -f discard-server discard-client *.o