CC=gcc
CFLAGS=-Wall -g -c

make: wireminnow-part9.o
	$(CC) wireminnow-part9.o -o wireminnow-part9

wireminnow-part9.o: wireminnow-part9.c
	$(CC) $(CFLAGS) wireminnow-part9.c

clean:
	rm *.o wireminnow-part9

